name: Convert Text to PDF

on:
  push:
    branches:
      - main  # ou votre branche par défaut
  pull_request:
    branches:
      - main  # ou votre branche par défaut

jobs:
  convert-text-to-pdf:
    runs-on: ubuntu-latest  # Utiliser une image Ubuntu pour l'installation de LaTeX
    
    steps:
      # Étape 1: Vérifier le code depuis le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Installer LaTeX
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full  # Installer l'ensemble complet de TeX Live

      # Étape 3: Convertir le fichier texte en PDF
      - name: Convert text to PDF
        run: |
          pdflatex requirements.tex  # Assurez-vous que votre fichier texte est bien converti en fichier .tex

      # Étape 4: Télécharger le fichier PDF généré
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-file
          path: ./document.pdf  # Changez ceci en fonction de l'emplacement et du nom du fichier PDF généré

