name: Create SQLite Table

on:
  push:
    branches:
      - main  # Déclenche l'action lors d'un push sur la branche principale

jobs:
  create-table:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Créer la base de données et la table
      - name: Create SQLite database and table
        run: |
          sqlite3 database.db <<EOF
          CREATE TABLE IF NOT EXISTS users (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              name TEXT NOT NULL,
              email TEXT UNIQUE NOT NULL
          );
          EOF

      # Étape 3 : Vérifier que la table a bien été créée
      - name: Check database schema
        run: sqlite3 database.db ".schema"

      # Étape 4 : Stocker la base de données en tant qu'artefact pour téléchargement
      - name: Upload SQLite database
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-database
          path: database.db


